[pytest] # Configurações do pytest para projetos Django
DJANGO_SETTINGS_MODULE = setup.settings # Indica ao pytest qual módulo de configurações do Django usar
python_files = test_*.py # Padrão para identificar arquivos de teste
pythonpath = . # Adiciona o diretório atual ao PYTHONPATH